#!/usr/bin/env bash
set -e

npm run clean
tsc -p config/tsconfig.esm.json
js_files=$(find dist/esm -name '*.js')
for js_file in $js_files; do
  mv "$js_file" "${js_file%.js}".mjs
done
tsc -p ./config/tsconfig.cjs.json
echo 'module.exports = debtSnowball;' >> dist/cjs/index.js
