#!/usr/bin/env bash
set -e

npm run clean
tsc -p config/tsconfig.esm.json
tsc -p ./config/tsconfig.cjs.json

echo 'module.exports = snowball;' >> dist/esm/index.js
echo 'module.exports = snowball;' >> dist/cjs/index.js
