# source: https://github.com/actions/stale
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          any-of-labels: dependencies
          stale-issue-message: 'Stale Issue - Deleting'
          stale-pr-message: 'Stale PR - Deleting'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          delete-branch: true
